---
name: Commitlint GitHub Action
author: Cedric van Putten <me@bycedric.com>
description: Use Commitlint in GitHub Actions
branding:
  icon: git-commit
  color: gray-dark
runs:
  using: node12
  main: build/index.js
input:
  config:
    description: Path to the config file.
  extends:
    description: Shareable configuration to extend.
  from:
    description: Lower end of the commit range to lint. (uses action context by default)
  to:
    description: Upper end of the commit range to lint. (uses action context by default)
